language: php

env:
  global:
    - GIT_NAME: "'Couscous auto deploy'"
    - GIT_EMAIL: phpactor@dantleech.com
    - GH_REF: github.com/phpactor/phpactor
    - secure: "VW6FdcejZkI5Qir/MqzTsDxGGmrPKr1CLrFZirkD9wHUehiaJr2Z8JixBQsZy7D1z9nEycdt6Yq4ZFqoI0mSUhElOO8AY96Wed4PjIIhJ3tJKta8Eoks0KtHT12qxaFmZvVAkqfzQ3RrtIexwTb2axS7/tQRE0ZhECGppUnCges/tjqTm0nRox96l4pdtTXXlWsjbLjyFhDdURZY0t5QXDKiNh0ctHswc3MrSCc9BcRsX5+zuz/E/0RAI+J0w2ghVWRj9eIeuhvf9zIiFZdA07B4V3TSdF0E2ftPli7YUyZA2KmQ/8MBOF3PBI48KhU+kt6iHFa1EDlqp4t2NqHaRUEtmaHhlv+0cXHmKF1xMKLbMQdnqTg/NeWa9p87wAJ4dnvF1k1I9T2c0opKM7D4hUDBkFsx62jlstVxjmv+STwdaAw8WDZUnyNOLczTrAEg7jzwroigd/mYF6/8hiNsol1PeQsVbJqsi/61y3T8WkjeqnJJYisRrXcgi09sJ64crnr4CW+PxBR/88ETp8mLeM3oBGn+Nh5FjOKPc9pAVoai6DgfeJZ3UATY+7i82Q5vRlG860axhLVqqt2nYMnjKDBwHnh6CNaPArT5hIQgq/9AmW30dhFXheHy8XKgJMiyUtgktBk2zx4YilwcZKtP2/Gb5DCTbdQPjLJAu9/h6w4="

php:
  - 7.0
  - 7.1
  - 7.2

sudo: false

cache:
  directories:
    - "$HOME/.composer/cache"

before_script:
  - git config --global user.email "you@example.com"
  - git config --global user.name "Your Name"
  - curl -OS http://couscous.io/couscous.phar
  - composer install
  - git clone https://github.com/junegunn/vader.vim.git

script:
  - ./.travis/vim-plugin-test.sh
  - vendor/bin/phpunit
  - if [ -n "${REPORTS_API_KEY}" ]; then vendor/bin/phpbench run --store; else vendor/bin/phpbench run; fi;
  - .travis/testdeps

after_success:
  - php couscous.phar travis-auto-deploy
